version: '3.2'
services:
  web_container:
    image: "${DOCKERHUB_USERNAME}/webapplication:latest"
    ports:
      - 80:8080
    environment:
      SPRING_DATASOURCE_URL: "${SPRING_DATASOURCE_URL}"
      SPRING_DATASOURCE_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"
      SPRING_DATASOURCE_USERNAME: "${SPRING_DATASOURCE_USERNAME}"


